name: Auto‑Translator (Standard)

on:
  push:
    paths:
      - '*.md'
      - '**/*.md'
    branches:
      - main
  workflow_dispatch:
    inputs:
      languages:
        description: 'Language codes (space separated)'
        required: false
        default: 'es fr de ar zh hi ja ru pt it ko tr nl pl sv ur he'

jobs:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Translation
        uses: kduma-actions/auto-translate-markdown@v1
        with:
          source_lang: 'en'
          target_langs: ${{ github.event.inputs.languages || 'es fr de ar zh hi ja ru pt it ko tr nl pl sv ur he' }}
          paths: '.'
          exclude_paths: '.git,.github,assets,tools,CHAIN,i18n,node_modules,__pycache__'
          commit_message: 'chore(i18n): auto‑translation by @T@'
          commit_user_name: '@T@ (Translator)'
          commit_user_email: 'translator@shiftopia.world'
