name: IPFS Mirror

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix Git directory ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Disable GPG signing for this workflow
        run: git config --global commit.gpgsign false

      - name: Create test file
        run: echo "IPFS test without GPG" > test.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add test.txt
          git commit -m "test: ipfs no-gpg" || echo "No changes"
          git push
